apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservices.fullname" . }}-config
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
  SERVICE_MODE: {{ .Values.config.serviceMode | quote }}
  JUPYTERHUB_BASE_URL: {{ .Values.config.jupyterHubBaseUrl | quote }}
  {{- range $key, $value := .Values.config.extra }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
