apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend-api.fullname" . }}-config
  labels:
    {{- include "frontend-api.labels" . | nindent 4 }}
data:
  SERVICE_MODE: {{ .Values.config.serviceMode | quote }}
  JUPYTERHUB_BASE_URL: {{ .Values.config.jupyterHubBaseUrl | quote }}
  {{- range $key, $value := .Values.config.extra }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
